config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'customers#index'

  get   'customers/checkout'
  get   'customers/date_change'
  post  'customers/search'
  get   'customers/search_date'
  patch 'customers/cancel'
  get   'customers/split_check'
  get   'customers/make_payment_request'
  get   'customers/callback_square'
  get   'discount_rules/new'
  get   'discount_rules/index'

  resource :customers, only: [:update]
  resources :customers

  resource :monthly_members

  namespace :admin do
    resources :users
    resources :customers
    resources :stores
    resources :discount_rules
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_one :payment, dependent: :destroy, autosave: true
  has_one :monthly_member, dependent: :destroy, autosave: true

  paginates_per 9

  scope :nums_of_checked_out, -> {
    where(check_in_time: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
        .where.not(check_out_time: nil).size
  }

  scope :nums_of_checked_in, -> {
    where(check_in_time: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day,
          check_out_time: nil).size
  }

  scope :customers_list, -> (d, current_user) {
    @customers = Customer.where('check_in_time >= ? AND check_in_time < ? AND store = ?',
                                d,
                                d.tomorrow,
                                current_user.store)
  }

  scope :customers_list_today, -> (current_user) {
    @customers = Customer.where('check_in_time >= ? AND check_in_time < ? AND store = ?',
                                Time.zone.now.beginning_of_day,
                                Time.zone.tomorrow.beginning_of_day,
                                current_user.store)
  }

  def self.make_payment_request(id, amount, currency, square_id)
    {
        amount_money: {
            amount: amount,
            currency_code: currency
        },
        callback_url: 'https://morning-shore-21493.herokuapp.com/customers/callback_square',
        client_id: square_id,
        version: '1.3',
        notes: 'Usage Time',
        state: id.to_s,
        options: {
            supported_tender_types: %w(CREDIT_CARD CASH OTHER SQUARE_GIFT_CARD)
        }
    }
  end
end

app/controllers/admin/customers_controller.rb
module Admin
  class CustomersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Customer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Customer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :customers_list_today, only: [:index, :create]

  def index
    @customer = Customer.new
    @num_of_checked_out = Customer.nums_of_checked_out
    @num_of_checked_in = Customer.nums_of_checked_in
  end

  def new
  end

  def show
  end

  # Check-In
  def create
    monthly_member_id = params[:customer][:monthly_member_id]
    if params[:customer][:kind].to_i == CustomerKind.find_by_kind('Monthly Member').id &&
        MonthlyMember.valid_monthly_member(monthly_member_id).empty?
      flash[:alert] = "id: #{monthly_member_id} isn't monthly member"
      redirect_back fallback_location: :index
      return
    else
      @customer = Customer.new(customer_params)
      @customer.update_attributes(
          check_in_time: Time.at(Time.zone.now.to_i / 60 * 60),
          store: current_user.store.id,
          rate_per_min: current_user.store.rate_per_min,
          monthly_member_id: monthly_member_id.empty? ? nil : monthly_member_id.to_i
      )
      @customer.build_payment
    end
    redirect_to customers_path
  end

  def search
    id = params[:search]
    if id.empty?
      redirect_to customers_path
    else
      @customer = Customer.new
      @customers = Customer.where(id: id).page(params[:page])
      render :index
    end
  end

  def search_date
    if params[:datepicker].nil? || params[:datepicker] == ''
      @date = Time.new.strftime("%Y-%m-%d")
    else
      @date = Time.parse(params[:datepicker]) rescue Time.zone.now
    end
    if Time.new.strftime("%Y-%m-%d").eql?(@date)
      redirect_to customers_path
    else
      @customer = Customer.new
      customers_list(@date)
      render :index
    end
  end

  #Check-Out

  def checkout
  end

  def date_change
    d = Time.parse(params[:date])
    @customers = Customer.where(check_in_time: d.beginning_of_day, check_out_time: d.end_of_day, store: current_user.store)
                     .page(params[:page])
                     .reverse_order
    redirect_to customers_path
  end

  def update
    @customer = Customer.find(params[:customer][:id])
    if @customer.update_attributes(customer_params)
      charge = params[:customer][:charge].gsub(/[^0-9]/, '').to_i
      @customer.charge = charge
      if PaymentMethod.find_by_payment_method('DEV_USE_ONLY').id == params[:customer][:payment_method].to_i
        redirect_to customers_path
      elsif (1..5) === params[:customer][:payment_method].to_i
        make_payment_request(@customer.id, charge)
      end
    else
      render :index
    end
  end

  def cancel
    @customer = Customer.find(params[:format])
    @customer.check_out_time = nil
    if @customer.save!
      redirect_to customers_path
    else
      render :index
    end
  end

  def callback_square
    cb = JSON.parse(URI.decode(params[:data])).with_indifferent_access
    if 'ok'.eql?(cb[:status])
      @customer = Customer.find(cb[:state])
      @customer.check_out_time = Time.at(Time.zone.now.to_i / 60 * 60)
      payment = Payment.create(
          transaction_id: cb[:transaction_id],
          client_transaction_id: cb[:client_transaction_id],
          status: cb[:status],
          error_code: cb[:error_code]
      )
      @customer.payment << payment
      if @customer.save!
        redirect_to customers_path
      else
        render :index
      end
    elsif 'error'.eql?(cb[:status])
      @customer.payment.error_code = cb[:error_code]
      flash[:alert] = cb[:error_code]
    end
  end

  def destroy
    if Customer.find_by(id: params[:id]).delete
      redirect_to customers_path
    end
  end

  def split_check
    @customer = Customer.find(params[:id])
    divided = @customer.dup
    divided.people = 1
    @customer.people -= 1

    begin
      divided.save!
      @customer.save!
      redirect_to customers_path
    rescue
      render :index
    end
  end

  def make_payment_request(id, amount)
    req = Customer.make_payment_request(id, amount, current_user.store.currency, Rails.application.secrets.square_client_id)
    redirect_to 'square-commerce-v1://payment/create?data=' + URI.encode(req.to_json)
  end

  private

  def customer_params
    params.require(:customer).permit(%i(
      id
      check_in_time
      check_out_time
      rate_per_min
      store
      charge
      people
      discount_percentage
      kind
      discount
      monthly_member_id
    ))
  end

  def customers_list(d)
    @customers = Customer.customers_list(d, current_user)
                     .page(params[:page])
                     .reverse_order
  end

  def customers_list_today
    @customers = Customer.customers_list_today(current_user)
                     .page(params[:page])
                     .reverse_order
  end
end

app/helpers/customer_helper.rb
module CustomerHelper

  def currency_symbol(currency)
    case currency
      when 'GBP'
        '&pound;'
      when 'EURO'
        '&euro;'
      when 'RUB'
        '&#x20BD;'
      when 'USD'
        '&#36;'
      when 'JPY'
        '&yen;'
    end
  end

  def curr_usage(check_in_time)
    Time.at((Time.zone.now - check_in_time).to_i).utc.strftime('%k:%M')
  end

  def curr_amount
    # TODO 今の時点での料金を計算する
  end
end

app/views/customers/_index.html.erb
<% @customers.each_with_index do |customer| %>
  <tr id="tr<%= customer.id %>" class="
    <% if customer.check_out_time.presence %>active<% end %>">
    <th scope="row">
      <%= customer.id.to_s(:delimited, delimiter: ' ') %>
    </th>
    <td>
      <% if customer.monthly_member_id.presence %><%= customer.monthly_member_id %><% end %>
    </td>
    <td>
      <%= customer.check_in_time.strftime("%H:%M") %>
    </td>
    <td>
      <div id="checkOutTime<%= customer.id %>" class="checkOutTime" data-checkout="
        <% if customer.check_out_time.presence %><%= customer.check_out_time.strftime('%FT%R') %><% end %>">
        <% if customer.check_out_time.presence %>
          <%= customer.check_out_time.strftime("%H:%M") %>
        <% end %>
      </div>
    </td>
    <td>
      <div id="usageTime<%= customer.id %>" data-id="<%= customer.id %>" class="usageTime"
           data-checkin="<%= customer.check_in_time.to_json.gsub(/\"/, '') %>">
        <%= curr_usage(customer.check_in_time) %>
      </div>
    </td>
    <td>
      <div id="people<%= customer.id %>"
           data-people="<%= customer.people %>"><%= customer.people %></div>
    </td>
    <td>
      <div id="kind<%= customer.id %>"
           data-kind="<%= customer.kind %>"
           data-kind-name="<%= CustomerKind.find_by_id(customer.kind).kind %>"
           data-currency="<%= current_user.store.currency %>">
        <%= CustomerKind.find_by_id(customer.kind).kind %>
      </div>
    </td>
    <td>
      <div id="currentCost<%= customer.id %>"
           data-currency="<%= current_user.store.currency %>"
           data-rate-per-min="<%= current_user.store.rate_per_min %>"
           data-day-cap-hour="<%= current_user.store.day_cap_hour %>"
           data-student-discount-percentage="<%= current_user.store.student_discount_percentage %>"
           data-charge="<%= customer.charge %>"
           class="currentCost">
      </div>
    </td>
    <td>
      <% if customer.check_out_time.blank? %>
        <%= link_to '#checkOut', class: 'btn btn-link',
                    data: {toggle: 'modal',
                           customer_id: customer.id,
                           people: customer.people,
                           kind: customer.kind,
                           check_in_time: customer.check_in_time.strftime('%FT%R'),
                           check_in_time_raw: customer.check_in_time.to_json.gsub(/\"/, '')
                    } do %>
          <%= icon('fas', 'sign-out-alt') %>
        <% end %>
      <% else %>
        <%= link_to customers_cancel_path(customer), method: :patch, class: 'btn btn-link',
                    data: {confirm: 'Are you sure to cancel this Check-Out?'} do %>
          <%= icon('fas', 'undo') %>
        <% end %>
      <% end %>
      <% unless customer.check_out_time %>
        <%= link_to customer_path(customer.id), method: :delete, class: 'btn btn-link',
                    data: {confirm: 'Are you sure to delete this Check-In?'} do %>
          <%= icon('far', 'trash-alt') %>
        <% end %>
      <% end %>
      <% if customer.people > 1 and not customer.check_out_time %>
        <%= link_to customers_split_check_path(id: customer.id), method: :get,
                    class: 'btn btn-link',
                    data: {confirm: 'Are you sure to Split the Check?'} do %>
          <%= icon('fas', 'percent') %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/customers/_modal_check_in.html.erb
<div class="modal fade" id="checkIn">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_with(model: Customer.new, method: :post, html: {class: 'form-horizontal'}) do |f| %>
        <div class="modal-header">
          Check-In
          <button type="button" class="close text-left" data-dismiss="modal" aria-label="Close">
            &times;
          </button>
        </div>
        <div class="modal-body" style="padding: 30px 30px 30px 30px;">
          <div class="form-group row" id="numberOfPeople">
            <%= f.label :people, 'People', class: 'col-sm-3 col-form-label text-sm-right' %>
            <div class="col-sm-9">
              <%= f.number_field(:people, in: 1..99, step: 1, value: 1, class: 'form-control') %>
            </div>
          </div>
          <div class="form-group row" id="customersKind">
            <%= f.label :kind, 'Kind', class: 'col-sm-3 col-form-label text-sm-right' %>
            <div class="col-sm-9">
              <%= f.collection_select :kind, CustomerKind.all, :id, :kind,
                                      {selected: CustomerKind.find_by_kind('Drop In').id},
                                      {class: 'form-control'} %>
            </div>
          </div>
          <div class="form-group row" id="monthlyMemberId" style="display: none">
            <%= f.label 'Member\'s ID', class: 'col-sm-3 col-form-label text-sm-right' %>
            <div class="col-sm-9"><%= f.number_field(:monthly_member_id, in: 1..99, step: 1, class: 'form-control') %></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-outline-secondary" data-dismiss="modal">
            <%= icon('fa', 'ban') %>
            Cancel
          </button>
          <%= button_tag type: :submit, id: 'checkInSubmit', class: 'btn btn-outline-primary' do %>
            <%= icon('fa', 'check') %>
            Check-In
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/_modal_check_out.html.erb
<div class="modal fade" id="checkOut" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <%= form_with(model: Customer.new, url: customers_path, method: :patch, remote: :false, html: {id: 'new_customer', class: 'form-horizontal'}) do |f| %>
        <input type="hidden" id="customer_id" name="customer[id]">
        <div class="modal-header">
          Check-Out
          <button type="button" class="close text-left" data-dismiss="modal" aria-label="Close">
            &times;
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <%= f.label :usage_time, 'Check-In', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="form-inline input-group col-sm-7">
              <%= f.datetime_local_field :check_in_time, id: 'checkintime', class: 'form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :usage_time, 'Check-Out', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="form-inline input-group col-sm-7">
              <%= f.datetime_local_field :check_out_time, id: 'checkouttime', class: 'form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :usage_time, 'Usage', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <%= content_tag :p, id: 'sub_total', class: 'text-right total' do %>
                <%= icon('far', 'clock') %>
              <% end %>
            </div>
          </div>
          <div class="form-group row" id="numberOfPeople">
            <%= f.label :people, 'People', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <%= f.number_field(:people, id: 'numpeople', in: 1..99, step: 1, value: 1, class: 'form-control') %>
            </div>
          </div>
          <div class="form-group row" id="customersKind">
            <%= f.label :kind, 'Kind', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <%= f.collection_select :kind, CustomerKind.all, :id, :kind, {}, {class: 'form-control', id: 'customer_kind'} %>
            </div>
          </div>
          <div class="form-group row" id="paymentMethod">
            <%= f.label :payment_method, 'Pay Method', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <%= f.collection_select :payment_method,
                                      Rails.env == 'production' ? PaymentMethod.all[1..3] : PaymentMethod.all[0..3],
                                      :id,
                                      :payment_method,
                                      {selected: Rails.env == 'production' ?
                                                     PaymentMethod.find_by_payment_method('CASH').id :
                                                     PaymentMethod.find_by_payment_method('DEV_USE_ONLY').id},
                                      {class: 'form-control', id: :payment_method} %>
            </div>
          </div>
          <div class="form-group row" id="discountPercent">
            <%= f.label :discount_percentage, 'Discount Rate', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <%= f.number_field(:discount_percentage, id: 'discount_per', in: 0...90, step: 1, value: 0, class: 'form-control') %>
              <div class="input-group-append">
                <%= f.label :discount_per, '%', class: 'input-group-text' %>
              </div>
            </div>
          </div>
          <div class="form-group row" id="discountDirect">
            <%= f.label :discount, 'Discount', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7">
              <div class="input-group-prepend">
                <%= f.label :charge, raw(currency_symbol(current_user.store.currency)), class: 'input-group-text' %>
              </div>
              <%= f.number_field(:discount, id: 'discount_direct', value: 0, class: 'form-control') %>
            </div>
          </div>
          <div class="form-group row" id="totalCost">
            <%= f.label :charge, 'Total', class: 'col-sm-4 text-sm-right control-label' %>
            <div class="input-group col-sm-7 float-right">
              <%= f.hidden_field :charge, id: 'total_cost_hidden' %>
              <%= content_tag :div, '', id: 'total_cost', class: 'total text-sm-right' %>
            </div>
          </div>
        </div>
        <div class="modal-footer" id="footerBar">
          <button type="button" class="btn btn-default btn-outline-secondary" data-dismiss="modal">
            <%= icon('fa', 'ban') %>
            Cancel
          </button>
          <%= button_tag type: :submit, id: 'checkOutSubmit', class: 'btn btn-default btn-outline-primary' do %>
            <%= icon('fa', 'check') %>
            Check-Out
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/_regist_monthly_member.html.erb
<div class="modal fade" id="monthlyMember" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <%= form_with model: MonthlyMember.new, local: true, html: {class: 'form-horizontal'} do |f| %>
        <div class="modal-header">
          Monthly Member Registration
          <button type="button" class="close text-left" data-dismiss="modal" aria-label="Close">
            &times;
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <%= f.label :start_date, 'Start Date', class: 'col-sm-3 text-sm-right' %>
            <div class="form-inline input-group col-sm-8">
              <%= f.date_field :start_date, id: 'startDate', class: 'form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :end_date, 'End Date', class: 'col-sm-3 text-sm-right control-label' %>
            <div class="form-inline input-group col-sm-8">
              <%= f.date_field :end_date, id: 'endDate', readonly: true, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :charge, 'Charge', class: 'col-sm-3 text-sm-right control-label' %>
            <div class="input-group col-sm-8">
              <div class="input-group-prepend">
                <%= f.label :charge, raw(currency_symbol(current_user.store.currency)), class: 'input-group-text' %>
              </div>
              <%= f.number_field(:charge, id: 'price', value: MonthlyMemberPrice.find_by_store_id(current_user.store.id).price, class: 'form-control') %>
            </div>
          </div>
        </div>
        <div class="modal-footer" id="footerBar">
          <button type="button" class="btn btn-default btn-outline-secondary" data-dismiss="modal">
            <%= icon('fa', 'ban') %>
            Cancel
          </button>
          <%= button_tag type: :submit, id: 'monthMemberSubmit', class: 'btn btn-default btn-outline-primary' do %>
            <%= icon('fa', 'check') %>
            Regist
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/checkin.html.erb
<h1>Customer#checkin</h1>
<p>Find me in app/views/customer/checkin.html.erb</p>

app/views/customers/edit.js.erb
$('#modal_check_out').html("<%= escape_javascript(render 'edit') %>")
$('#modal_check_out').modal('show')

app/views/customers/index.html.erb
<%= render 'layouts/navbar' %>
<%= render 'layouts/table_toolbar' %>

<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>M/M</th>
    <th>In</th>
    <th>Out</th>
    <th>Usage</th>
    <th><i class="fas fa-users"></i></th>
    <th>Kind</th>
    <th>Charge</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <%= render 'index' %>
  </tbody>
</table>
<div class="pull-left">
  <%= icon('far', 'circle') %> <%= @num_of_checked_in %>
  <%= icon('far', 'check-circle') %> <%= @num_of_checked_out %>
</div>
<div class="pull-right">
  <%= paginate(@customers) %>
</div>

<%= render 'modal_check_in' %>
<%= render 'modal_check_out' %>
<%= render 'regist_monthly_member' %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= form_for(@customer, :url => {:controller => 'customer', :action => 'create'}) do |f| %>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
    <%= f.submit 'Create' %>
<% end %>

app/views/customers/new.js.erb
$('#modal_check_in').html("<%= escape_javascript(render 'new') %>")
$('#modal_check_in').modal('show')