config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'customers#index'

  get   'customers/checkout'
  get   'customers/date_change'
  post  'customers/search'
  get   'customers/search_date'
  patch 'customers/cancel'
  get   'customers/split_check'
  get   'customers/make_payment_request'
  get   'customers/callback_square'
  get   'discount_rules/new'
  get   'discount_rules/index'

  resource :customers, only: [:update]
  resources :customers

  resource :monthly_members

  namespace :admin do
    resources :users
    resources :customers
    resources :stores
    resources :discount_rules
  end
end

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <%= link_to 'Funshin', customers_path, {class: 'navbar-brand'} %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to '#monthlyMember', class: 'nav-link', data: {toggle: 'modal'} do %><i class="far fa-id-card"></i>
          Monthly Member
        <% end %>
      </li>
      <% if current_user.has_role? :admin %>
        <li class="nav-item">
          <%= link_to admin_customers_path, class: 'nav-link' do %>
            <%= icon('fas', 'cog') %>
            Admin Dashboard
          <% end %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= icon('fas', 'user') %>
          <%= current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to edit_user_registration_path, href: '#', class: 'dropdown-item' do %>
            <%= icon('fas', 'pencil-alt') %>
            Edit User
          <% end %>
          <%= link_to destroy_user_session_path, href: '#', method: :delete, class: 'dropdown-item' do %>
            <%= icon('fas', 'sign-out-alt') %>
            Log Out
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_table_toolbar.html.erb
<div class="row">
  <div class="col">
    <form>
      <div class="form-group float-left" style="padding: 10px 10px 10px 0px;">
        <%= link_to '#checkIn', data: {toggle: 'modal'}, class: 'btn btn-outline-primary' do %>
          <%= icon('fas', 'plus') %>
        <% end %>
      </div>
    </form>
  </div>
  <div class="col float-right">
    <%= form_with url: customers_search_date_path, method: :post, class: 'form-inline pull-right' do |f| %>
      <div class="input-group date" style="padding: 10px 0px 10px 10px;">
        <%= text_field_tag :datepicker,
                           @date ? @date.strftime('%Y-%m-%d') : Time.zone.now.strftime('%Y-%m-%d'),
                           class: 'form-control date-picker', type: 'date' %>
        <span class="input-group-btn">
      <%= button_tag type: :submit, class: 'btn btn-default btn-outline-primary' do %>
      <%= icon('far', 'calendar') %>
      <% end %>
    </span>
      </div>
    <% end %>
  </div>
  <div class="col  float-right">
    <%= form_with url: customers_search_path, method: :get, class: 'form-inline pull-right' do |f| %>
      <div class="input-group" style="padding: 10px 0px 10px 10px;">
        <%= text_field_tag :search, '', class: 'form-control', type: 'number', placeholder: 'ID' %>
        <span class="input-group-btn">
    <%= button_tag type: :submit, class: 'btn btn-default btn-outline-primary' do %>
      <%= icon('fas', 'search') %>
    <% end %>
    </span>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funshin</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
</head>

<body>
<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
</body>
</html>